export const IPC_CHANNELS = {
  API_REQUEST: "api:request",
  STREAM_SUBSCRIBE: "stream:subscribe",
  STREAM_UNSUBSCRIBE: "stream:unsubscribe",
  STREAM_EVENT: "stream:event",

  CONFIG_GET_ENVIRONMENTS: "config:getEnvironments",
  CONFIG_ADD_ENVIRONMENT: "config:addEnvironment",
  CONFIG_REMOVE_ENVIRONMENT: "config:removeEnvironment",
  CONFIG_UPDATE_ENVIRONMENT: "config:updateEnvironment",
  CONFIG_ADD_ENDPOINT: "config:addEndpoint",
  CONFIG_REMOVE_ENDPOINT: "config:removeEndpoint",
  CONFIG_SET_ACTIVE_ENDPOINT: "config:setActiveEndpoint",
  CONFIG_GET_SELECTED_ENVIRONMENT_ID: "config:getSelectedEnvironmentId",
  CONFIG_SET_SELECTED_ENVIRONMENT_ID: "config:setSelectedEnvironmentId",
  CONFIG_MIGRATE_FROM_LOCAL_STORAGE: "config:migrateFromLocalStorage",
  CONFIG_EXCHANGE_PAIRING_CODE: "config:exchangePairingCode",
  CONFIG_REMOVE_SESSION_TOKEN: "config:removeSessionToken",
  CONFIG_SET_OPENCODE_ENDPOINT: "config:setOpenCodeEndpoint",
  CONFIG_SET_INFRA_OPENCODE_ENDPOINT: "config:setInfraOpenCodeEndpoint",
  CONFIG_SET_MAIN_VM: "config:setMainVm",
  CONFIG_GET_MAIN_VM_ID: "config:getMainVmId",
  CONFIG_GET_PROJECT_PICKUP_LABELS: "config:getProjectPickupLabels",
  CONFIG_SET_PROJECT_PICKUP_LABELS: "config:setProjectPickupLabels",
  CONFIG_GET_PROJECT_PIPELINE_LABELS: "config:getProjectPipelineLabels",
  CONFIG_SET_PROJECT_PIPELINE_LABELS: "config:setProjectPipelineLabels",
  CONFIG_GET_CHAT_SESSIONS: "config:getChatSessions",
  CONFIG_ADD_CHAT_SESSION: "config:addChatSession",
  CONFIG_REMOVE_CHAT_SESSION: "config:removeChatSession",
  CONFIG_UPDATE_CHAT_SESSION: "config:updateChatSession",
  CONFIG_PIN_CHAT_SESSION: "config:pinChatSession",
  CONFIG_RENAME_CHAT_SESSION: "config:renameChatSession",
  CONFIG_REORDER_CHAT_SESSIONS: "config:reorderChatSessions",
  CONFIG_GET_EXPANDED_PROJECTS: "config:getExpandedProjects",
  CONFIG_SET_EXPANDED_PROJECTS: "config:setExpandedProjects",
  CONFIG_EXPORT_BOOTSTRAP_SEED: "config:exportBootstrapSeed",
  CONFIG_IMPORT_BOOTSTRAP_SEED: "config:importBootstrapSeed",
  CONFIG_CHECK_RESTORE_AVAILABLE: "config:checkRestoreAvailable",
  CONFIG_PULL_RESTORE: "config:pullRestore",
  CONFIG_GET_STAMP: "config:getConfigStamp",
  CONFIG_STAMP_CHECKED_SET_MAIN_VM: "config:stampCheckedSetMainVm",
  CONFIG_FORCE_SET_MAIN_VM: "config:forceSetMainVm",
  CONFIG_SWEEP_EPHEMERAL_SESSIONS: "config:sweepEphemeralSessions",

  CONNECTION_GET_STATUS: "connection:getStatus",
  CONNECTION_GET_ENDPOINT_HEALTH: "connection:getEndpointHealth",
  CONNECTION_RETRY: "connection:retry",
  CONNECTION_STATUS: "connection:status",
  CONNECTION_ENDPOINT_HEALTH: "connection:endpointHealth",
  CONNECTION_NETWORK_CHANGED: "connection:networkChanged",

  TAILSCALE_PEERS: "tailscale:peers",

  OPENCODE_GET_STATUS: "opencode:getStatus",
  OPENCODE_REFRESH_STATUS: "opencode:refreshStatus",
  OPENCODE_STATUS: "opencode:status",

  VM_WIZARD_LIST_SSH_HOSTS: "vmWizard:listSshHosts",
  VM_WIZARD_START: "vmWizard:start",
  VM_WIZARD_PROGRESS: "vmWizard:progress",
  VM_WIZARD_CANCEL: "vmWizard:cancel",
  VM_WIZARD_RESPOND_CONSENT: "vmWizard:respondConsent",
  VM_WIZARD_RESPOND_SERVICE_SELECTION: "vmWizard:respondServiceSelection",
  VM_WIZARD_RESPOND_RUNTIME_CONSENT: "vmWizard:respondRuntimeConsent",
  VM_WIZARD_RESPOND_HOST_KEY: "vmWizard:respondHostKey",

  INFRA_EXECUTE_ACTION: "infra:executeAction",
  INFRA_GET_STATUS: "infra:getStatus",
  INFRA_GET_PLATFORM: "infra:getPlatform",

  BUDGET_GET_WATCHES: "budget:getWatches",
  BUDGET_ADD_WATCH: "budget:addWatch",
  BUDGET_REMOVE_WATCH: "budget:removeWatch",
  BUDGET_UPDATE_WATCH: "budget:updateWatch",
  BUDGET_GET_BREACHES: "budget:getBreaches",
  BUDGET_ADD_BREACH: "budget:addBreach",
  BUDGET_DISMISS_BREACH: "budget:dismissBreach",

  INBOX_GET_ITEMS: "inbox:getItems",
  INBOX_GET_DISMISSED_IDS: "inbox:getDismissedIds",
  INBOX_DISMISS_ITEM: "inbox:dismissItem",
  INBOX_QUERY_FLEET: "inbox:queryFleet",
  INBOX_RESOLVE_ITEM: "inbox:resolveItem",
  INBOX_GET_RESOLVED_ITEMS: "inbox:getResolvedItems",
  INBOX_PRUNE_RESOLVED_ITEMS: "inbox:pruneResolvedItems",

  WATCH_GET_WATCHES: "watch:getWatches",
  WATCH_ADD_WATCH: "watch:addWatch",
  WATCH_REMOVE_WATCH: "watch:removeWatch",
  WATCH_TRIP_WATCH: "watch:tripWatch",

  NOTIFICATION_SEND: "notification:send",
  NOTIFICATION_SET_MUTED: "notification:setMuted",
  NOTIFICATION_IS_MUTED: "notification:isMuted",
  NOTIFICATION_NAVIGATE: "notification:navigate",

  OUTAGE_ESCALATION: "outage:escalation",
  OUTAGE_RESOLVE: "outage:resolve",
  OUTAGE_GET_ESCALATIONS: "outage:getEscalations",

  REACHABILITY_GET_STATUS: "reachability:getStatus",
  REACHABILITY_GET_ALL: "reachability:getAll",
  REACHABILITY_STATUS: "reachability:status",

  TRANSCRIPT_GET_MESSAGES: "transcript:getMessages",
  TRANSCRIPT_APPEND_MESSAGE: "transcript:appendMessage",
  TRANSCRIPT_APPEND_MESSAGES: "transcript:appendMessages",
  TRANSCRIPT_UPDATE_MESSAGE: "transcript:updateMessage",
  TRANSCRIPT_DELETE_SESSION: "transcript:deleteSession",

  MCP_GET_STATUS: "mcp:getStatus",
  MCP_CONNECT: "mcp:connect",
  MCP_DISCONNECT: "mcp:disconnect",
  MCP_CALL_TOOL: "mcp:callTool",
  MCP_STATUS: "mcp:status",

  AGENT_SEND_PROMPT: "agent:sendPrompt",
  AGENT_INTERRUPT: "agent:interrupt",
  AGENT_STREAM_EVENT: "agent:streamEvent",
  AGENT_LIST_MODELS: "agent:listModels",

  LOOP_SHAPE_CACHE_GET_CACHED: "loopShapeCache:getCached",
  LOOP_SHAPE_CACHE_GET_ALL: "loopShapeCache:getAll",
  LOOP_SHAPE_CACHE_REFRESH: "loopShapeCache:refresh",
  LOOP_SHAPE_CACHE_UPDATE: "loopShapeCache:update",

  SIBLING_DECLINE_IS_DECLINED: "siblingDecline:isDeclined",
  SIBLING_DECLINE_RECORD_DECLINE: "siblingDecline:recordDecline",

  SETTINGS_GET: "settings:get",
  SETTINGS_UPDATE: "settings:update",

  LOG_WRITE: "log:write",

  CREDENTIAL_TAMPERED: "credential:tampered",
  CREDENTIAL_GET_SECURITY_AUDIT_EVENTS: "credential:getSecurityAuditEvents",
} as const;
